### ISSUE TITLE
Uncaught TypeError: getEditor(...).lineLengthForBufferRow is not a function

### ISSUE THREAD

**Issue by BabylonSix** [ajile/word-jumper#22]
[Enter steps to reproduce below:]

if you move left at beginning of a line, the error is thrown.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [word-jumper](https://github.com/ajile/word-jumper) package, v0.3.0
### Stack Trace

Uncaught TypeError: getEditor(...).lineLengthForBufferRow is not a function

```
At /Users/bravo/.atom/packages/word-jumper/lib/word-jumper.coffee:96

TypeError: getEditor(...).lineLengthForBufferRow is not a function
  at move (/Users/bravo/.atom/packages/word-jumper/lib/word-jumper.coffee:96:26)
  at moveCursors (/Users/bravo/.atom/packages/word-jumper/lib/word-jumper.coffee:134:3)
  at atom-workspace.atom.commands.add.word-jumper:move-left (/Users/bravo/.atom/packages/word-jumper/lib/word-jumper.coffee:148:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```
### Commands

```
  2x -0:35.3.0 word-jumper:move-left (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17 word-jumper:move-left (atom-text-editor.editor.is-focused)
     -0:16 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:14.9.0 word-jumper:move-right (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.6.0 word-jumper:move-left (atom-text-editor.editor.is-focused)
     -0:11 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:11 core:cancel (atom-text-editor.editor.is-focused)
     -0:09.4.0 word-jumper:move-left (atom-text-editor.editor.is-focused)
     -0:08.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:07.2.0 word-jumper:move-left (atom-text-editor.editor.is-focused)
  6x -0:06.5.0 word-jumper:move-right (atom-text-editor.editor.is-focused)
  6x -0:05.6.0 word-jumper:move-left (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "disabledPackages": [
      "linter-tidy",
      "linter-csslint",
      "linter-csslint"
    ]
  },
  "word-jumper": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
aligner, v0.17.1
aligner-css, v1.2.0
aligner-python, v1.0.1
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atom-beautify, v0.28.17
atom-jade, v0.3.0
autoclose-html, v0.19.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.13
emmet, v2.3.14
gulp-snippets, v0.6.2
language-SCSS, v0.4.0
language-babel, v2.3.1
language-svg, v0.9.0
linter, v1.10.0
linter-coffeescript, v1.0.0
linter-eslint, v4.0.0
linter-jade, v0.3.2
linter-sass-lint, v0.4.1
linter-scss-lint, v2.4.0
linter-shellcheck, v1.0.2
linter-stylint, v2.0.1
markdown-preview-plus, v2.2.2
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
monokai-seti, v0.7.0
pigments, v0.18.1
preview-plus, v1.2.6
react, v0.12.10
seti-ui, v0.8.1
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by josh-berry** [comment]
Still happens in Atom 1.7.2.

**Comment by SnijkoVladislav** [comment]
in vim mode. when caret in start of line and we move left

**Comment by drewshaver** [comment]
I have a fix for this waiting to be pulled into master. Not sure if @ajile is still maintaining this project though.

https://github.com/drewshaver/word-jumper/commit/c05d60081a90cb000cfbb17a9d2047b1a76bfa7d

**Comment by gilbertohasnofb** [comment]
This issue is still affecting this package. It would be really great if @ajile would have the chance to check and perhaps merge the PR mentioned above

**Comment by gilbertohasnofb** [comment]
Just found https://atom.io/packages/word-jumper-deluxe which seems to address this issue.
